USE [BookLog]
GO

/****** Object:  Index [IX_CreatorRoleBook]    Script Date: 12.06.2023 13:34:03 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_CreatorRoleBook] ON [dbo].[contributesTo]
(
	[RoleID] ASC,
	[CreatorID] ASC,
	[WorkID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


